#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/home/dpd4k4/CA1_model/CA1_model_env/lib/python3.6/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/home/dpd4k4/CA1_model/CA1_model_env/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/dpd4k4/CA1_model/biophys_components/mechanisms/modfiles/x86_64/.libs/libnrnmech.so" "$@"
